/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "bb463b8b-b76c-4f6a-9726-65ab5730b69b",
    title: "Generic Concrete Table",
    para: "Provident quo provident. Harum ullam pariatur quos est quod. Ea quisquam esse quia expedita commodi autem.",
    src: "video4.mp4",
    views: 234513,
    likes: 2937,
    catergoryName: "entertainment",
  },
  {
    _id: "ac1c6062-7261-44e6-8ebf-8879914576ad",
    title: "Unbranded Concrete Computer",
    para: "Maiores incidunt occaecati iusto laborum facere. Deleniti dolorem quibusdam. Veniam perspiciatis et nisi aut corporis laboriosam. Est soluta accusamus officiis ut excepturi.",
    src: "video7.mp4",
    views: 669314,
    likes: 2683,
    catergoryName: "news",
  },
  {
    _id: "d94a8d21-5ce3-4237-9318-e2aebf079488",
    title: "Rustic Plastic Keyboard",
    para: "Aut voluptatem excepturi eligendi voluptates iste eius iure. Molestiae at voluptas quo ex. Ipsa incidunt corporis vel in unde. Iste asperiores consequatur ex quidem omnis inventore deserunt. Eligendi officiis voluptatem. In omnis labore consequatur nisi.",
    src: "video13.mp4",
    views: 513128,
    likes: 294,
    catergoryName: "news",
  },
  {
    _id: "8132e57a-3d48-4dd8-aa5c-5d26d0578899",
    title: "Sleek Plastic Chair",
    para: "Expedita et ut quia ut nostrum ducimus occaecati veniam ut. Voluptatibus error quaerat porro error. Aut aliquid qui harum minus officiis neque. Animi maiores et aliquid. Dolorem beatae et molestiae consequatur sed rerum qui voluptates unde. Explicabo accusantium exercitationem illum.",
    src: "video13.mp4",
    views: 241827,
    likes: 5690,
    catergoryName: "music",
  },
  {
    _id: "71c7b806-b4d6-42cc-84a4-fa613a7e8b67",
    title: "Intelligent Cotton Car",
    para: "Error ut dicta aut qui qui vel. Suscipit ipsum molestiae inventore placeat nesciunt. Laboriosam facere odio beatae nobis vero quia. Et voluptates molestiae magni beatae vitae atque eos optio. Vitae nihil accusamus natus et quia. Sed dolores vel quis totam et.",
    src: "video12.mp4",
    views: 841279,
    likes: 74,
    catergoryName: "news",
  },
  {
    _id: "87e99634-b46b-4ad0-9a70-ab67b1f8110a",
    title: "Awesome Frozen Cheese",
    para: "Sunt et aut corporis cumque quos distinctio. Ab quia autem consectetur occaecati nemo molestiae nisi temporibus soluta. Illo deleniti aut sit id quia. Nulla placeat amet sed esse aut doloribus dolores. Ipsum sint nobis sint. Sunt fuga laudantium ipsam quas quos ipsam.",
    src: "video12.mp4",
    views: 47339,
    likes: 1326,
    catergoryName: "gaming",
  },
  {
    _id: "11730c4e-6054-45fd-88a8-017cf6611278",
    title: "Tasty Granite Pants",
    para: "Aspernatur quibusdam mollitia quia dolore dignissimos id porro corporis. Eveniet consectetur culpa delectus quo et. Et rerum accusantium repudiandae ut ab quas vel. Error asperiores dolores.",
    src: "video4.mp4",
    views: 575135,
    likes: 3743,
    catergoryName: "movies",
  },
  {
    _id: "3f193a46-ab46-45c0-b528-7289644a60de",
    title: "Handcrafted Steel Sausages",
    para: "Omnis debitis quae autem quo ut. Omnis officiis qui impedit aliquid a aut et cum officiis. Ex praesentium non quasi voluptatem repellat earum quidem.",
    src: "video12.mp4",
    views: 68152,
    likes: 8461,
    catergoryName: "gaming",
  },
  {
    _id: "1d9408b1-0915-435e-a558-b9a3f94a3416",
    title: "Unbranded Cotton Chair",
    para: "Officia alias hic necessitatibus iste laboriosam. Harum alias sit deleniti necessitatibus molestiae qui. Explicabo ab nihil voluptate. Quis ut vero aut accusantium rem et eaque soluta excepturi. Occaecati est culpa vel quo suscipit aliquid aliquid voluptates reprehenderit. Facere reprehenderit consequatur ea et aut.",
    src: "video14.mp4",
    views: 465927,
    likes: 9081,
    catergoryName: "news",
  },
  {
    _id: "54ae4734-5656-4ecd-bb7f-86d3b184b251",
    title: "Awesome Rubber Towels",
    para: "Error soluta consectetur. Cum omnis numquam quas minima vitae quod culpa. Et suscipit officia perspiciatis quisquam eligendi dicta. Voluptatibus culpa quia incidunt aut maxime quas omnis dignissimos velit.",
    src: "video3.mp4",
    views: 820575,
    likes: 4205,
    catergoryName: "coding",
  },
  {
    _id: "dcc3252f-8a8c-46b5-b876-c0a0011a56f2",
    title: "Sleek Cotton Ball",
    para: "Quod non et quam impedit. Voluptatem nulla voluptatibus blanditiis. Minima sed recusandae atque. Voluptatum voluptates et ipsa cupiditate. Dolorem atque nihil dignissimos culpa eaque facere ipsa. Sit laudantium rerum temporibus et aut.",
    src: "video6.mp4",
    views: 166773,
    likes: 6120,
    catergoryName: "nature",
  },
  {
    _id: "372e55d4-874e-4f2d-a5cf-df16aa96a401",
    title: "Fantastic Concrete Fish",
    para: "In similique amet voluptatem. Sit aut rem fuga nulla odio rerum nihil ullam quis. Accusamus officia minima aspernatur voluptatem explicabo sint error et possimus. Eos cupiditate quis aut doloribus.",
    src: "video2.mp4",
    views: 902812,
    likes: 8375,
    catergoryName: "movies",
  },
  {
    _id: "67a9f031-0a02-4bee-a776-98dd7a336c32",
    title: "Licensed Wooden Computer",
    para: "Labore aliquam nihil qui aliquid rerum minima id repellat et. A facilis omnis. Autem omnis dolorum. Sit sunt aut est. Minus repudiandae cum.",
    src: "video8.mp4",
    views: 51901,
    likes: 2054,
    catergoryName: "movies",
  },
  {
    _id: "97f43c92-890f-48e0-b20c-f5e4e669b932",
    title: "Fantastic Wooden Pizza",
    para: "Et saepe vel dolores. Molestiae est nemo dolor sint debitis sint eos aut velit. Corporis et voluptatibus corporis voluptas laboriosam dolor mollitia cum. Est recusandae enim qui maxime voluptatum. Et natus ea labore.",
    src: "video14.mp4",
    views: 758862,
    likes: 988,
    catergoryName: "nature",
  },
  {
    _id: "315a274e-cc85-40ef-99d0-ea6642b90b0a",
    title: "Small Concrete Computer",
    para: "Sed saepe porro a ea a quibusdam deleniti. Et eaque sed unde est eos sit similique. Quia nemo excepturi at possimus in aut. Illum eveniet dolorem ea provident. Iure aut dolore sed est.",
    src: "video14.mp4",
    views: 37392,
    likes: 8846,
    catergoryName: "nature",
  },
  {
    _id: "585e28d0-42cc-4478-bd5d-4ef56de9acd5",
    title: "Refined Wooden Sausages",
    para: "Eius aut aut minus blanditiis id nulla porro. Porro eaque ipsa. Sint quod autem. Et nam laudantium non iusto quo ea qui. Mollitia cupiditate et.",
    src: "video7.mp4",
    views: 710298,
    likes: 6634,
    catergoryName: "news",
  },
  {
    _id: "87070cb0-b1f8-4e77-aaf7-c356c1aa8397",
    title: "Rustic Frozen Pizza",
    para: "Voluptatem dolorem ullam facere earum reiciendis voluptates maiores neque temporibus. Et placeat quia ut et non quia aut aut reprehenderit. Expedita omnis est vel voluptas doloremque dolor.",
    src: "video10.mp4",
    views: 466810,
    likes: 1609,
    catergoryName: "gaming",
  },
  {
    _id: "858fb74a-658f-45a5-b213-f5f19e073cc7",
    title: "Refined Concrete Table",
    para: "Et ad repellat sed animi. Facilis tenetur et. Et dolorem in quia minima expedita porro voluptas facilis. Dolores neque eum maiores debitis tempora impedit officia veniam.",
    src: "video9.mp4",
    views: 615895,
    likes: 9674,
    catergoryName: "coding",
  },
  {
    _id: "af9b8dc7-1103-4fc7-8595-5c862cb73d41",
    title: "Incredible Granite Chair",
    para: "Voluptatem eum earum quia et iure. Quibusdam aspernatur provident quia et enim. Atque at laboriosam architecto est qui. Maxime accusamus fuga asperiores dicta eius.",
    src: "video11.mp4",
    views: 611671,
    likes: 5271,
    catergoryName: "nature",
  },
  {
    _id: "9f94eb40-5ea1-4cb2-b58a-3a9a93af2deb",
    title: "Generic Cotton Car",
    para: "Error adipisci ut accusantium omnis omnis quo vel. Eos dolores aut autem nam voluptatem impedit suscipit. Et ut delectus minima illo. Praesentium occaecati ut. Ut et facere laboriosam molestiae error voluptatem rerum.",
    src: "video13.mp4",
    views: 747326,
    likes: 1704,
    catergoryName: "gaming",
  },
  {
    _id: "8468dcf9-0809-47c5-8aea-fde3c5386244",
    title: "Handcrafted Plastic Gloves",
    para: "Incidunt fugit laborum omnis voluptas qui accusamus quo qui. Beatae fuga doloribus iste tempore aut. Possimus vel perspiciatis occaecati quia autem et eaque. Non est accusantium itaque. Modi asperiores tempora laboriosam at dolorem. Sequi aliquid delectus ut similique consequuntur voluptatem maiores dolorem.",
    src: "video12.mp4",
    views: 100624,
    likes: 8994,
    catergoryName: "nature",
  },
  {
    _id: "8014095c-ebf0-4df2-96f3-133aa7955178",
    title: "Tasty Plastic Soap",
    para: "Enim pariatur iure optio iste non perferendis. Pariatur nulla et tempora omnis magnam. Aliquid doloribus repellendus eum sunt. Eaque est voluptatem iusto voluptates velit reprehenderit delectus.",
    src: "video11.mp4",
    views: 63690,
    likes: 4323,
    catergoryName: "coding",
  },
  {
    _id: "93541dc5-6163-4ad5-b74b-ac1fb06fe24e",
    title: "Tasty Cotton Hat",
    para: "Culpa est doloremque magnam maiores. Perferendis adipisci optio sapiente. Quos dolorum facere facilis voluptatum ea officia. Qui rerum reiciendis rerum libero dolore.",
    src: "video4.mp4",
    views: 718080,
    likes: 151,
    catergoryName: "gaming",
  },
  {
    _id: "3f776bc3-cd16-4f88-99d6-8a9dca4f7b6d",
    title: "Incredible Steel Soap",
    para: "Expedita laboriosam aut quibusdam. Illum laborum et aspernatur necessitatibus mollitia quae deleniti sed. Et sit deserunt consequatur. Dolorum ipsam voluptas quia nemo vel facere sunt possimus animi. Ea aut asperiores sint perferendis iste debitis maxime.",
    src: "video6.mp4",
    views: 903178,
    likes: 8621,
    catergoryName: "movies",
  },
  {
    _id: "265bfa98-95e3-412d-9e19-de6b03ef3c4d",
    title: "Intelligent Wooden Chips",
    para: "Tempore quisquam est. Iure libero nesciunt vero quos et dolor tempore quia cumque. Praesentium occaecati accusamus voluptatem eligendi quisquam saepe delectus facere.",
    src: "video1.mp4",
    views: 520290,
    likes: 2488,
    catergoryName: "coding",
  },
  {
    _id: "5720c8d6-6251-4672-85f3-646b0e640d01",
    title: "Incredible Metal Bacon",
    para: "Et perferendis qui neque illum quod. Id repellat facere modi aliquid cum aliquid praesentium. Quo in quam qui occaecati culpa earum commodi ducimus. Laboriosam fugit adipisci. Voluptas qui sed asperiores quo commodi et magnam debitis aliquid. Nisi dignissimos quidem.",
    src: "video7.mp4",
    views: 12737,
    likes: 8579,
    catergoryName: "nature",
  },
  {
    _id: "56e68737-47d5-4a77-ae82-983a8f900480",
    title: "Gorgeous Soft Shirt",
    para: "Sint voluptas officia atque quidem accusantium et nemo eum. Libero ipsam suscipit quia impedit nostrum maiores tenetur. Dicta consequatur laudantium minima inventore omnis ut ipsam ratione dolorem. Sint voluptatem nihil eligendi quod ut velit consequatur. Exercitationem nulla vitae. Dolores dolorum quis expedita rerum error et.",
    src: "video1.mp4",
    views: 36044,
    likes: 2215,
    catergoryName: "movies",
  },
  {
    _id: "3779b1ca-d562-47c6-91e4-b673096eacd9",
    title: "Generic Soft Shirt",
    para: "Corrupti officiis facilis aliquid quibusdam et. Dignissimos eum repellat qui vel repellendus adipisci qui quae. Ipsum voluptatibus quia beatae sunt nihil. Rerum ipsa quisquam itaque ducimus ut ad voluptatem.",
    src: "video1.mp4",
    views: 530829,
    likes: 5954,
    catergoryName: "news",
  },
  {
    _id: "244a645e-bea1-4728-bd0b-d354b7063415",
    title: "Intelligent Concrete Shirt",
    para: "Ut sint repellat et voluptatem nihil. Vitae totam quis iure doloribus qui natus. Temporibus doloribus aperiam. Vitae odio aut tempore perferendis ullam et iusto aliquam.",
    src: "video12.mp4",
    views: 996570,
    likes: 5754,
    catergoryName: "nature",
  },
  {
    _id: "84dfdd02-62ea-481b-9f13-3efa76944d73",
    title: "Rustic Soft Hat",
    para: "Et ab fuga. Qui illo voluptas occaecati ea ut harum amet. Sunt voluptas exercitationem quia blanditiis iusto eos. Consequuntur qui odit id quasi nihil omnis quis possimus nihil.",
    src: "video12.mp4",
    views: 328997,
    likes: 9579,
    catergoryName: "entertainment",
  },
  {
    _id: "2f2d7bde-c288-42b6-9bc5-2059ab2ba245",
    title: "Handmade Cotton Table",
    para: "Fugit explicabo eum quia molestias aut impedit sit similique aut. Vel molestiae non mollitia totam aut. Et accusamus tempore aut eveniet fugit doloribus et. Itaque eligendi voluptatem sint.",
    src: "video3.mp4",
    views: 17400,
    likes: 9443,
    catergoryName: "nature",
  },
  {
    _id: "a1ce6972-d02d-4b26-b814-d36ad7c8d374",
    title: "Handmade Soft Gloves",
    para: "Eum incidunt et. Odit commodi exercitationem. Occaecati sit quia consequatur labore nobis. Aut quas architecto quasi dolores sunt porro.",
    src: "video13.mp4",
    views: 977166,
    likes: 2099,
    catergoryName: "movies",
  },
  {
    _id: "71719331-b044-442d-8651-d74ab4bf07f5",
    title: "Rustic Fresh Fish",
    para: "Deleniti accusamus dicta asperiores nobis adipisci. Qui magnam quas quia delectus doloribus. Inventore deserunt quia incidunt distinctio porro maxime quis. Nulla odio reiciendis voluptatibus consequatur ut tenetur voluptas ea consequuntur. Ab molestiae consequuntur omnis alias et. Aspernatur quod voluptas voluptatem placeat distinctio vero incidunt eum.",
    src: "video8.mp4",
    views: 492114,
    likes: 1588,
    catergoryName: "coding",
  },
  {
    _id: "b595ebcc-ad6d-4ec8-9ab3-f8eaf601993e",
    title: "Gorgeous Cotton Pizza",
    para: "Dolorem voluptas harum occaecati eos amet numquam alias animi. Esse impedit et non deleniti illo quam quam laudantium vel. Ipsum sed sequi et quia atque mollitia. Consequuntur sunt labore dolore rerum sed eius sunt.",
    src: "video11.mp4",
    views: 899840,
    likes: 5980,
    catergoryName: "movies",
  },
  {
    _id: "64922d73-f360-43ce-b98b-a8105cdf5b8c",
    title: "Licensed Fresh Chips",
    para: "Quis aut ducimus nostrum perspiciatis. Voluptatem voluptates deleniti voluptatem ad quia. Culpa ut iste vitae omnis aut perferendis eos maxime. Voluptate recusandae vel architecto laborum qui consequatur molestiae dolore. Sunt voluptatem dolores corporis eligendi minus ipsam dolor numquam. Earum quod modi dolor dolor modi laudantium cumque.",
    src: "video5.mp4",
    views: 794505,
    likes: 3885,
    catergoryName: "entertainment",
  },
];
